//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighSpeedRail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HighSpeedRail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商務車廂 / 升等.
        /// </summary>
        internal static string Bussiness {
            get {
                return ResourceManager.GetString("Bussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跑馬燈.
        /// </summary>
        internal static string DetailType_Announcement {
            get {
                return ResourceManager.GetString("DetailType_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖片.
        /// </summary>
        internal static string DetailType_Picture {
            get {
                return ResourceManager.GetString("DetailType_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影片.
        /// </summary>
        internal static string DetailType_Video {
            get {
                return ResourceManager.GetString("DetailType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 孕婦/年長/無障疑專用.
        /// </summary>
        internal static string Elderly {
            get {
                return ResourceManager.GetString("Elderly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業客戶.
        /// </summary>
        internal static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定期票/回數票.
        /// </summary>
        internal static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當日票/預售票.
        /// </summary>
        internal static string Today_PreSale {
            get {
                return ResourceManager.GetString("Today_PreSale", resourceCulture);
            }
        }
    }
}
